name: safebox
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
   flutter: 
    sdk: flutter
   get:
   shared_preferences: 
   cached_network_image:
   flutter_svg: 
   google_sign_in: 
   pin_code_fields: 
   smooth_page_indicator: 
   sms_autofill: 
   flutter_svg_provider: 
   dotted_border: 
   intl: 
   dio:
   intl_phone_field: 
   fluttertoast: 
   simple_grouped_listview: 
   flutter_contacts: 
   file_picker: 
   background_downloader: 
   path_provider:
   firebase_core: 
   firebase_auth:
   percent_indicator: 
   photo_manager: 
   flutter_archive: 
   webview_flutter: 
   disk_space_plus:
   another_telephony:
   chat_bubbles: 
   carousel_slider: 
   marquee: 
   permission_handler: ^11.3.1

   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: "assets/images/safeboxicon.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
    - family: Sofia Pro
      fonts: 
        - asset: assets/fonts/SofiaProSemiBold.ttf
          weight: 600
        - asset: assets/fonts/SofiaProMedium.ttf
          weight: 500
        - asset: assets/fonts/SofiaPro.ttf
          weight: 400
    - family: Open Sans
      fonts: 
        - asset: assets/fonts/OpenSansSemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSansBold.ttf
          weight: 700
    - family: SF Pro Text
      fonts: 
        - asset: assets/fonts/SFProTextRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProTextMedium.ttf
          weight: 500


