// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN3zVZRz0zlb6rZSxwhbG7SiO7QaaPBCM',
    appId: '1:217520767118:web:89628d85438ba7363a89df',
    messagingSenderId: '217520767118',
    projectId: 'safebox-2c284',
    authDomain: 'safebox-2c284.firebaseapp.com',
    storageBucket: 'safebox-2c284.appspot.com',
    measurementId: 'G-JH3M3JSBS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-iMAegZkROyFvUDNUEWRJxXShFTWNvEU',
    appId: '1:217520767118:android:1cff225821e4549c3a89df',
    messagingSenderId: '217520767118',
    projectId: 'safebox-2c284',
    storageBucket: 'safebox-2c284.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJX7m-sR23QI6FeTIFO0GnBvVyS48mNkA',
    appId: '1:217520767118:ios:f1b735ca04c2d8043a89df',
    messagingSenderId: '217520767118',
    projectId: 'safebox-2c284',
    storageBucket: 'safebox-2c284.appspot.com',
    androidClientId: '217520767118-hi246sa6a2sgdj6au6490qj90spv6i5o.apps.googleusercontent.com',
    iosClientId: '217520767118-2vao8aae7gubgmbh1cuvvv5uhdqbv12s.apps.googleusercontent.com',
    iosBundleId: 'com.example.safebox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJX7m-sR23QI6FeTIFO0GnBvVyS48mNkA',
    appId: '1:217520767118:ios:d27ac18ee2bddc8e3a89df',
    messagingSenderId: '217520767118',
    projectId: 'safebox-2c284',
    storageBucket: 'safebox-2c284.appspot.com',
    androidClientId: '217520767118-hi246sa6a2sgdj6au6490qj90spv6i5o.apps.googleusercontent.com',
    iosClientId: '217520767118-i8ht0007634sbi8kbp7jcefsj00i4538.apps.googleusercontent.com',
    iosBundleId: 'com.example.safebox.RunnerTests',
  );
}
